### PR TITLE
Rename watch icons to correspond with AB files

### PR DESCRIPTION
**Pull request by nadyaA**
When generating icons and splash screens the files that are generated do not correspond with the files used from plugin.
When people start using the plugin they will expect the generated images to work properly. If we do not have same filenames, they will not.
We need to change the filenames in the plugin to avoid breaking user experience – if someone has already generated their icons, they will have two empty if we change the filenames in AB.
So it is better from user point of view to change them in the plugin.

ping @galexandrov

### CODE REVIEW

**Comment by galexandrov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by EddyVerbruggen** [comment]
Nice! Would you prefer a retag (of 0.6.2) or a new version in this case?

**Comment by galexandrov** [comment]
Retagging will be better :smile: and I will clean the server cache

**Comment by nadyaA** [comment]
Thanks, guys :smiley_cat:

**Comment by EddyVerbruggen** [comment]
0.6.2 has just been retagged :beers:

**Pull request merged**
