### PR TITLE
Re-attach wormhole listener on screen's willActivate

### PR DESCRIPTION
**Pull request by bfischer1121**
Fix for #4

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi @bfischer1121 thanks for these changes!
I will test them today and fix things in case something is broken.

**Comment by EddyVerbruggen** [comment]
Working great! I made minor changes: the `imageData` attribute is now called `data` and the group's  `namedBackgroundImage` is now called `backgroundImageNamed` (because that's what iOS calls it and I don't want to confuse anyone).

Btw, do you have an example of using that group background image? Not the JS code, but the configuration of the image in the watch app?

And thanks again, you've definitely improved this plugin and I love the base64 image feature!

**Comment by bfischer1121** [comment]
Hi Eddy,

I'm happy the changes could get merged in. The names make more sense too.

If you add a background image to the watch app's "Images.xcassets" it can be used in the group's "Background" config. For some reason, it only shows up when you start typing the name, not in the dropdown.

Best wishes,
Blake

**Comment by EddyVerbruggen** [comment]
Thanks!

**Pull request merged**
